# Default parameters of environmental_model

#Crosswalk,Junction,ArrowMarking,Obstacle,RoadClosure,SpeedLimit,StartLine,Unidentified
# Column is observation, row is true class.
wonham_measurement_matrix : [0.5, 0.1, 0.1, 0.1, 0.1, 0.05, 0.1, 0.01,
                             0.1, 1.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.01,
                             0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.01,
                             0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1, 0.01,
                             0.1, 0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1,
                             0.28, 0.1, 0.1, 0.1, 0.1, 0.4, 0.1, 0.01, #speedLimit is only relevant if we pass it so we can reduce the entry
                             0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0.5, 0.01,
                             0.1, 0.13, 0.1, 0.12, 0.1, 0.1, 0.1, 0.3] #the 4. entry in this row determines how long obstacles are tracked
scale_probabilities : 1.0 #exponent for every entry in the wonham_measurement_matrix.
min_prob_publishing : [0.0, 0.0, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0]
min_prob_new_tracking : [0.2, 0.2, 0.2, 0.2, 0.4, 0.2, 0.2, 0.0]
decay_max_distance : 1.3
decay_min_prob : 0.3

no_passing_zone: {
  decrease_factor: 0.8,
  threshold: 1.1,
  merge_distance: 0.7,
  number_msg_consecutive: 0
}

road_closure: {
  road_closure_start_distance: 0.4,
  road_closure_end_distance: 0.2,
  min_assumed_road_closure_length: 0.3
}

speed_limit: {
  saved_speed_limit_msgs_count: 5,
  alpha : 0.9
}

junction_roi_right_min_x: 0.35
junction_roi_right_min_y: -1.2
junction_roi_right_max_x: 0.75
junction_roi_right_max_y: -0.25
junction_roi_center_min_x: 0.35
junction_roi_center_min_y: -0.4
junction_roi_center_max_x: 0.8
junction_roi_center_max_y: 0.5

road_closure_roi_width: 0.45 # ~lane width

crosswalk_roi_width: 1.5
crosswalk_roi_height: 0.45
crosswalk_look_at_dist: 0.3 #if distance from vehicle to crosswalk is smaller no look at region is generated
